spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:roomEscape

  jpa:
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
        show_sql: true


security:
  jwt:
    secret_key: 7Iqk7ZSE66eB67aA7Yq4X+ujuOydtOyKpOy8gOydtO2UhF/rqaTrsoRf67mE67CA67KI7Zi4
    expiry: 3600000 # 1시간


